package com.sharjeel.newsapp.util

data class CountryData(val name: String, val flag: String)

object CountryUtils {
    val allCountries = listOf(
        CountryData("Afghanistan", "🇦🇫"),
        CountryData("Albania", "🇦🇱"),
        CountryData("Algeria", "🇩🇿"),
        CountryData("Andorra", "🇦🇩"),
        CountryData("Angola", "🇦🇴"),
        CountryData("Antigua and Barbuda", "🇦🇬"),
        CountryData("Argentina", "🇦🇷"),
        CountryData("Armenia", "🇦🇲"),
        CountryData("Australia", "🇦🇺"),
        CountryData("Austria", "🇦🇹"),
        CountryData("Azerbaijan", "🇦🇿"),
        CountryData("Bahamas", "🇧🇸"),
        CountryData("Bahrain", "🇧🇭"),
        CountryData("Bangladesh", "🇧🇩"),
        CountryData("Barbados", "🇧🇧"),
        CountryData("Belarus", "🇧🇾"),
        CountryData("Belgium", "🇧🇪"),
        CountryData("Belize", "🇧🇿"),
        CountryData("Benin", "🇧🇯"),
        CountryData("Bhutan", "🇧🇹"),
        CountryData("Bolivia", "🇧🇴"),
        CountryData("Bosnia and Herzegovina", "🇧🇦"),
        CountryData("Botswana", "🇧🇼"),
        CountryData("Brazil", "🇧🇷"),
        CountryData("Brunei", "🇧🇳"),
        CountryData("Bulgaria", "🇧🇬"),
        CountryData("Burkina Faso", "🇧🇫"),
        CountryData("Burundi", "🇧🇮"),
        CountryData("Cabo Verde", "🇨🇻"),
        CountryData("Cambodia", "🇰🇭"),
        CountryData("Cameroon", "🇨🇲"),
        CountryData("Canada", "🇨🇦"),
        CountryData("Central African Republic", "🇨🇫"),
        CountryData("Chad", "🇹🇩"),
        CountryData("Chile", "🇨🇱"),
        CountryData("China", "🇨🇳"),
        CountryData("Colombia", "🇨🇴"),
        CountryData("Comoros", "🇰🇲"),
        CountryData("Congo", "🇨🇬"),
        CountryData("Costa Rica", "🇨🇷"),
        CountryData("Croatia", "🇭🇷"),
        CountryData("Cuba", "🇨🇺"),
        CountryData("Cyprus", "🇨🇾"),
        CountryData("Czech Republic", "🇨🇿"),
        CountryData("Denmark", "🇩🇰"),
        CountryData("Djibouti", "🇩🇯"),
        CountryData("Dominica", "🇩🇲"),
        CountryData("Dominican Republic", "🇩🇴"),
        CountryData("Ecuador", "🇪🇨"),
        CountryData("Egypt", "🇪🇬"),
        CountryData("El Salvador", "🇸🇻"),
        CountryData("Equatorial Guinea", "🇬🇶"),
        CountryData("Eritrea", "🇪🇷"),
        CountryData("Estonia", "🇪🇪"),
        CountryData("Eswatini", "🇸🇿"),
        CountryData("Ethiopia", "🇪🇹"),
        CountryData("Fiji", "🇫🇯"),
        CountryData("Finland", "🇫🇮"),
        CountryData("France", "🇫🇷"),
        CountryData("Gabon", "🇬🇦"),
        CountryData("Gambia", "🇬🇲"),
        CountryData("Georgia", "🇬🇪"),
        CountryData("Germany", "🇩🇪"),
        CountryData("Ghana", "🇬🇭"),
        CountryData("Greece", "🇬🇷"),
        CountryData("Grenada", "🇬🇩"),
        CountryData("Guatemala", "🇬🇹"),
        CountryData("Guinea", "🇬🇳"),
        CountryData("Guinea-Bissau", "🇬🇼"),
        CountryData("Guyana", "🇬🇾"),
        CountryData("Haiti", "🇭🇹"),
        CountryData("Honduras", "🇭🇳"),
        CountryData("Hungary", "🇭🇺"),
        CountryData("Iceland", "🇮🇸"),
        CountryData("India", "🇮🇳"),
        CountryData("Indonesia", "🇮🇩"),
        CountryData("Iran", "🇮🇷"),
        CountryData("Iraq", "🇮🇶"),
        CountryData("Ireland", "🇮🇪"),
        CountryData("Israel", "🇮🇱"),
        CountryData("Italy", "🇮🇹"),
        CountryData("Jamaica", "🇯🇲"),
        CountryData("Japan", "🇯🇵"),
        CountryData("Jordan", "🇯🇴"),
        CountryData("Kazakhstan", "🇰🇿"),
        CountryData("Kenya", "🇰🇪"),
        CountryData("Kiribati", "🇰🇮"),
        CountryData("Korea, North", "🇰🇵"),
        CountryData("Korea, South", "🇰🇷"),
        CountryData("Kosovo", "🇽🇰"),
        CountryData("Kuwait", "🇰🇼"),
        CountryData("Kyrgyzstan", "🇰🇬"),
        CountryData("Laos", "🇱🇦"),
        CountryData("Latvia", "🇱🇻"),
        CountryData("Lebanon", "🇱🇧"),
        CountryData("Lesotho", "🇱🇸"),
        CountryData("Liberia", "🇱🇷"),
        CountryData("Libya", "🇱🇾"),
        CountryData("Liechtenstein", "🇱🇮"),
        CountryData("Lithuania", "🇱🇹"),
        CountryData("Luxembourg", "🇱🇺"),
        CountryData("Madagascar", "🇲🇬"),
        CountryData("Malawi", "🇲🇼"),
        CountryData("Malaysia", "🇲🇾"),
        CountryData("Maldives", "🇲🇻"),
        CountryData("Mali", "🇲🇱"),
        CountryData("Malta", "🇲🇹"),
        CountryData("Marshall Islands", "🇲🇭"),
        CountryData("Mauritania", "🇲🇷"),
        CountryData("Mauritius", "🇲🇺"),
        CountryData("Mexico", "🇲🇽"),
        CountryData("Micronesia", "🇫🇲"),
        CountryData("Moldova", "🇲🇩"),
        CountryData("Monaco", "🇲🇨"),
        CountryData("Mongolia", "🇲🇳"),
        CountryData("Montenegro", "🇲🇪"),
        CountryData("Morocco", "🇲🇦"),
        CountryData("Mozambique", "🇲🇿"),
        CountryData("Myanmar", "🇲🇲"),
        CountryData("Namibia", "🇳🇦"),
        CountryData("Nauru", "🇳🇷"),
        CountryData("Nepal", "🇳🇵"),
        CountryData("Netherlands", "🇳🇱"),
        CountryData("New Zealand", "🇳🇿"),
        CountryData("Nicaragua", "🇳🇮"),
        CountryData("Niger", "🇳🇪"),
        CountryData("Nigeria", "🇳🇬"),
        CountryData("North Macedonia", "🇲🇰"),
        CountryData("Norway", "🇳🇴"),
        CountryData("Oman", "🇴🇲"),
        CountryData("Pakistan", "🇵🇰"),
        CountryData("Palau", "🇵🇼"),
        CountryData("Palestine", "🇵🇸"),
        CountryData("Panama", "🇵🇦"),
        CountryData("Papua New Guinea", "🇵🇬"),
        CountryData("Paraguay", "🇵🇾"),
        CountryData("Peru", "🇵🇪"),
        CountryData("Philippines", "🇵🇭"),
        CountryData("Poland", "🇵🇱"),
        CountryData("Portugal", "🇵🇹"),
        CountryData("Qatar", "🇶🇦"),
        CountryData("Romania", "🇷🇴"),
        CountryData("Russia", "🇷🇺"),
        CountryData("Rwanda", "🇷🇼"),
        CountryData("Saint Kitts and Nevis", "🇰🇳"),
        CountryData("Saint Lucia", "🇱🇨"),
        CountryData("Saint Vincent", "🇻🇨"),
        CountryData("Samoa", "🇼🇸"),
        CountryData("San Marino", "🇸🇲"),
        CountryData("Sao Tome and Principe", "🇸🇹"),
        CountryData("Saudi Arabia", "🇸🇦"),
        CountryData("Senegal", "🇸🇳"),
        CountryData("Serbia", "🇷🇸"),
        CountryData("Seychelles", "🇸🇨"),
        CountryData("Sierra Leone", "🇸🇱"),
        CountryData("Singapore", "🇸🇬"),
        CountryData("Slovakia", "🇸🇰"),
        CountryData("Slovenia", "🇸🇮"),
        CountryData("Solomon Islands", "🇸🇧"),
        CountryData("Somalia", "🇸🇴"),
        CountryData("South Africa", "🇿🇦"),
        CountryData("South Sudan", "🇸🇸"),
        CountryData("Spain", "🇪🇸"),
        CountryData("Sri Lanka", "🇱🇰"),
        CountryData("Sudan", "🇸🇩"),
        CountryData("Suriname", "🇸🇷"),
        CountryData("Sweden", "🇸🇪"),
        CountryData("Switzerland", "🇨🇭"),
        CountryData("Syria", "🇸🇾"),
        CountryData("Taiwan", "🇹🇼"),
        CountryData("Tajikistan", "🇹🇯"),
        CountryData("Tanzania", "🇹🇿"),
        CountryData("Thailand", "🇹🇭"),
        CountryData("Timor-Leste", "🇹🇱"),
        CountryData("Togo", "🇹🇬"),
        CountryData("Tonga", "🇹🇴"),
        CountryData("Trinidad and Tobago", "🇹🇹"),
        CountryData("Tunisia", "🇹🇳"),
        CountryData("Turkey", "🇹🇷"),
        CountryData("Turkmenistan", "🇹🇲"),
        CountryData("Tuvalu", "🇹🇻"),
        CountryData("Uganda", "🇺🇬"),
        CountryData("Ukraine", "🇺🇦"),
        CountryData("United Arab Emirates", "🇦🇪"),
        CountryData("United Kingdom", "🇬🇧"),
        CountryData("United States", "🇺🇸"),
        CountryData("Uruguay", "🇺🇾"),
        CountryData("Uzbekistan", "🇺🇿"),
        CountryData("Vanuatu", "🇻🇺"),
        CountryData("Vatican City", "🇻🇦"),
        CountryData("Venezuela", "🇻🇪"),
        CountryData("Vietnam", "🇻🇳"),
        CountryData("Yemen", "🇾🇪"),
        CountryData("Zambia", "🇿🇲"),
        CountryData("Zimbabwe", "🇿🇼")
    )
}
